#!/bin/sh

#   convert old FSL scripts from using avw* to using fsl*
#
#   Steve Smith, FMRIB Image Analysis Group
#
#   Copyright (C) 2007 University of Oxford
#
#   SHCOPYRIGHT

if [ $# -lt 1 ] ; then
  echo "Usage: $0 [list of scripts to convert]" ;
  exit 1 ;
fi

for s in $@ ; do

    echo "
----- Processing script $s (will create backup in ${s}_avw)"

    /bin/cp $s ${s}_avw

    # remove "++"
    for p in avw2ascii avwcc avwcpgeom avwcreatehd avwhd avwinterleave avwmaths avwmerge avwnvols avwroi avwsplit avwstats ; do
	sed "s/${p}++/${p}/g" $s > ${s}_tmp ; /bin/mv ${s}_tmp $s
    done

    # convert "avw" to "fsl"
    for p in avw2afni avw2ascii avwanimate avwcc avwcheck avwchfiletype avwchpixdim avwcomplex avwconv avwcpgeom avwcreatehd avwedithd avwfft avwfill avwhd avwinfo avwinterleave avwmaths avwmeants avwmerge avwnvols avworient avwpspec avwroi avwsize avwslice avwsplit avwstats avwswapdim avwval ; do
	q=`echo $p | sed 's/avw/fsl/g'`
	sed "s/${p}/${q}/g" $s > ${s}_tmp ; /bin/mv ${s}_tmp $s
    done

    # convert MNI152 references
    sed "s/etc\/standard/data\/standard/g" $s > ${s}_tmp ; /bin/mv ${s}_tmp $s
    sed "s/avg152T1_brain_mask_dil2/avg152T1_brain_mask_dil/g" $s > ${s}_tmp ; /bin/mv ${s}_tmp $s
    sed "s/avg152T1/MNI152_T1_2mm/g" $s > ${s}_tmp ; /bin/mv ${s}_tmp $s

    # warn about "ip"
    w=`cat $s | grep "ip "`
    if [ "$w" != "" ] ; then
	echo "--- Warning - hand-editing may be required in file ${s} if the following line(s) contain calls to the \"ip\" program,
    as ip no londer exists in FSL (use fslmaths instead):
$w"
    fi

    # warn about "-ero2"
    w=`cat $s | grep fslmaths | grep " -ero2 "`
    if [ "$w" != "" ] ; then
	echo "--- Warning - hand-editing may be required in file ${s}; in the following line, probably change \"-ero2\" to \"-kernel 2D -ero\"
$w"
    fi

    # warn about "-dil2"
    w=`cat $s | grep fslmaths | grep " -dil2 "`
    if [ "$w" != "" ] ; then
	echo "--- Warning - hand-editing may be required in file ${s}; in the following line, probably change \"-dil2\" to \"-kernel 2D -dilF\"
$w"
    fi

    # warn about "-dil"
    w=`cat $s | grep fslmaths | grep " -dil "`
    if [ "$w" != "" ] ; then
	echo "--- Warning - hand-editing may be required in file ${s}; in the following line, probably change \"-dil\" to \"-dilF\"
$w"
    fi

    # warn about "susan_smooth"
    w=`cat $s | grep susan_smooth`
    if [ "$w" != "" ] ; then
	echo "--- Warning - hand-editing may be required in file ${s}; in the following line, probably change \"susan_smooth\" to \"susan\" note that argument order has changed
$w"
    fi

    # warn about datatype changing in avwmaths_*
    for p in fsl2ascii fslcc fslinterleave fslmaths fslroi bet ; do
	w=`cat $s | grep ${p}_8UI`
	if [ "$w" != "" ] ; then
	    echo "--- hand-editing required in ${s} : in the following line(s), change \"${p}_8UI\" to \"${p}\" and end the command with \"-odt char\""
	    echo $w
	fi
	w=`cat $s | grep ${p}_16SI`
	if [ "$w" != "" ] ; then
	    echo "--- hand-editing required in ${s} : in the following line(s), change \"${p}_16SI\" to \"${p}\" and end the command with \"-odt short\""
	    echo $w
	fi
	w=`cat $s | grep ${p}_32SI`
	if [ "$w" != "" ] ; then
	    echo "--- hand-editing required in ${s} : in the following line(s), change \"${p}_32SI\" to \"${p}\" and end the command with \"-odt int\""
	    echo $w
	fi
	w=`cat $s | grep ${p}_32R`
	if [ "$w" != "" ] ; then
	    echo "--- hand-editing required in ${s} : in the following line(s), change \"${p}_32R\" to \"${p}\" and end the command with \"-odt float\""
	    echo $w
	fi
	w=`cat $s | grep ${p}_64R`
	if [ "$w" != "" ] ; then
	    echo "--- hand-editing required in ${s} : in the following line(s), change \"${p}_64R\" to \"${p}\" and end the command with \"-odt double\""
	    echo $w
	fi
    done

done  

