#!/bin/sh
set -e

#   Extended syntax for fslswapdim
#
#   Mark Jenkinson
#   FMRIB Image Analysis Group
#
#   Copyright (C) 2007-2008 University of Oxford
#
#   SHCOPYRIGHT


get_axis(){
    # search for either $1 or its reverse in $2 $3 $4
    # e.g. get_axis RL AP SI LR would return -z (as $1 = $4 but backwards)
    # whereas get_axis RL AP SI RL would return z (as $1 = $4)
    ax="";
    pre="";
    k2=`echo $1 | tr RLAPSI LRPAIS`;
    for fn in "$2:x" "$3:y" "$4:z" ; do
	ff=`echo $fn | sed 's/:.*//'`;
	aa=`echo $fn | sed 's/.*://'`;
	if [ $ff = $1 ] ; then ax=$aa ; fi
	if [ $ff = $k2 ] ; then ax=$aa ; pre="-" ; fi
    done
    ax="${pre}${ax}";
    echo $ax;
}

if [ $# -lt 4 ] ; then
  echo "Usage: fslswapdim <input> <a> <b> <c> [output]

  where a,b,c represent the new x,y,z axes in terms of the
  old axes.  They can take values of -x,x,y,-y,z,-z
  or RL,LR,AP,PA,SI,IS (in the case of nifti inputs)
  e.g.  fslswapdim invol y x -z outvol
  or    fslswapdim invol RL PA IS outvol
  where the latter will convert to axial slicing 
  (to match the avg152 images)
  If the output name is not specified the equivalent 
  transformation matrix is written to the standard output
  "
  exit 1;
fi


filetype=`$FSLDIR/bin/fslval $1 file_type`;
if [ $filetype = "ANALYZE-7.5" ] ; then
    nifti=no;
else 
    nifti=yes;
fi

orient=yes;
if [ $nifti = yes ] ; then
    if [ `$FSLDIR/bin/fslval $1 sform_code` -gt 0 ] ; then
	labs=`$FSLDIR/bin/fslhd $1 | grep sform_.orient | sed 's/[^A-Z]//g'`;
    elif [ `$FSLDIR/bin/fslval $1 qform_code` -gt 0 ] ; then
	labs=`$FSLDIR/bin/fslhd $1 | grep qform_.orient | sed 's/[^A-Z]//g'`;
    else
	labs="RL PA IS";  # default - but not safe
	orient=no;
    fi
fi

uselabels=no

comm1="$FSLDIR/bin/fslswapdim_exe $1"
comm2=""
swaplabs=""
for fn in $2 $3 $4 ; do
    cc=`echo Q$fn | sed 's/[RLAPIS]//g'`;
    if [ $cc = "Q" ] ; then
	uselabels=yes;
	if [ $nifti = no ] ; then
	    echo "Cannot use RLAPSI notation for non-nifti files"
	    exit 2
	fi
	if [ $orient = no ] ; then
	    echo "Cannot use RLAPSI notation for nifti files without either sform or qform set"
	    exit 2
	fi
	cc=`get_axis $fn $labs`;
    else 
	cc=$fn;
    fi
    comm2="$comm2 $cc";
    swaplabs="$swaplabs $cc"
done

# check if just a simple copy is good enough (only if an output filename is specified)
if [ "$swaplabs" = " x y z" ] ; then
    if [ X$5 != X ] ; then
	if [ `$FSLDIR/bin/remove_ext $1` != `$FSLDIR/bin/remove_ext $5` ] ; then
	    comm="$FSLDIR/bin/imcp $1 $5"
	    $comm
	    exit 0
	fi
    else
	cat $FSLDIR/etc/flirtsch/ident.mat
	exit 0
    fi
fi


# Check if the labels are used *and* it is doing a left-right inversion
if [ $uselabels = yes ] ; then
    # the line below just checks the swapping syntax - it does not require the true image, as any will do since the arguments are now reduced to x/y/z format
    check="`$FSLDIR/bin/fslswapdim_exe $FSLDIR/data/standard/MNI152_T1_2mm_brain $comm2 --checkLR`"
    wl=`echo $check | grep -i changed | wc -l`;
    if [ $wl -gt 0 ] ; then
	echo "Cannot perform requested swap (NEUROLOGICAL/RADIOLOGICAL storage inverted)"
	echo "Try the following command instead:"
	arg234=`echo "$2 $3 $4" | sed 's/RL/LRXX/g' | sed 's/LR/RL/g' | sed 's/RLXX/LR/g' | sed 's/-x/XX-x/g' | sed 's/ x / -x /g' | sed 's/XX-x/x/g'`;
	echo "fslswapdim $1 $arg234 $5"
	exit 1
    fi
fi

comm="$comm1 $comm2 $5"

# verbose?
#echo $comm

$comm

