"""Read existing CON07 artifacts only; no tensor fitting or model command."""
from pathlib import Path
import argparse,hashlib,json,socket
import nibabel as nib
import numpy as np
p=argparse.ArgumentParser();p.add_argument('--root',required=True);p.add_argument('--output',required=True);a=p.parse_args();r=Path(a.root);out=Path(a.output);assert not out.exists()
ref=r/'task_02/official_modeling_CPU_budget_raw10_v1/sub-CON07';diag=r/'task_02/actual_CPU_budget_comparison_v3/sub-CON07/tensor_same_input'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
files={'official_direction':ref/'direction.nii.gz','CPU_direction':diag/'direction_cpu.nii.gz','official_FA':ref/'fa.nii.gz','CPU_FA':diag/'fa_cpu.nii.gz','brain_mask':ref/'brain_mask.nii.gz','official_tensor':ref/'tensor.nii.gz','consumer':ref/'consumer_contract.json','CPU_diagnostic':diag/'report.json'}
consumer=json.loads(files['consumer'].read_text());dr=json.loads(files['CPU_diagnostic'].read_text());assert consumer['execution_completed'] and consumer['state']=='completed'
for k,n in [('official_direction','principal_direction'),('official_FA','FA'),('brain_mask','brain_mask')]:assert sha(files[k])==consumer['files'][n]['sha256']
assert sha(files['brain_mask'])==dr['input_sha256']['brain_mask'];assert dr['source_sha256']=='258938a5f20ee7a6efc2fc1c50af5c93412030a60b78036438e8473f072e3b91'
for key,contract_key in [('dwi','official_corrected_dwi'),('gradient','official_gradient_mrtrix')]:
    path=Path(consumer['files'][contract_key]['path']);digest=sha(path);assert digest==consumer['files'][contract_key]['sha256']==dr['input_sha256'][key];files[key]=path
images={k:nib.load(v) for k,v in files.items() if k not in ('consumer','CPU_diagnostic','dwi','gradient')};base=images['official_FA']
for im in images.values():assert im.shape[:3]==base.shape[:3] and np.allclose(im.affine,base.affine,rtol=0,atol=1e-6)
data={k:im.get_fdata(dtype=np.float32) for k,im in images.items()};left=data['CPU_direction'].astype(np.float64);right=data['official_direction'].astype(np.float64);mask=data['brain_mask']>0
valid=mask & np.isfinite(left).all(-1)&np.isfinite(right).all(-1)&(np.linalg.norm(left,axis=-1)>0)&(np.linalg.norm(right,axis=-1)>0)
coords=np.argwhere(valid);l=left[valid];v=right[valid];angle=np.degrees(np.arccos(np.clip(np.abs(np.sum(l*v,-1)/(np.linalg.norm(l,axis=-1)*np.linalg.norm(v,axis=-1))),0,1)))
assert abs(angle.max()-dr['direction_antipodal_degrees']['max'])<1e-10
rows=[]
for index in np.argsort(angle)[-10:][::-1]:
 c=tuple(coords[index]);coeff=data['official_tensor'][c].astype(np.float64);assert coeff.shape==(6,)
 d11,d22,d33,d12,d13,d23=coeff;t=np.array([[d11,d12,d13],[d12,d22,d23],[d13,d23,d33]]);values,vectors=np.linalg.eigh(t);order=np.argsort(np.abs(values));picked=int(order[-1]);ev=vectors[:,picked]
 deg=lambda x,y:float(np.degrees(np.arccos(np.clip(abs(np.dot(x,y))/(np.linalg.norm(x)*np.linalg.norm(y)),0,1))))
 rows.append({'voxel_index_zero_based':list(map(int,c)),'world_mm':(base.affine@np.r_[c,1])[:3].tolist(),'angle_degrees':float(angle[index]),'brain_mask':bool(mask[c]),'official_FA':float(data['official_FA'][c]),'CPU_FA':float(data['CPU_FA'][c]),'official_tensor_coefficients_D11_D22_D33_D12_D13_D23':coeff.tolist(),'official_eigenvalues_algebraic_ascending':values.tolist(),'algebraic_top_gap':float(values[-1]-values[-2]),'absolute_top_gap':float(abs(values[order[-1]])-abs(values[order[-2]])),'relative_absolute_top_gap':float((abs(values[order[-1]])-abs(values[order[-2]]))/max(abs(values))), 'official_saved_vector':right[c].tolist(),'CPU_saved_vector':left[c].tolist(),'official_tensor_absmax_eigenvector':ev.tolist(),'official_vector_vs_official_absmax_eigenvector_degrees':deg(right[c],ev),'CPU_vector_vs_official_absmax_eigenvector_degrees':deg(left[c],ev),'official_vector_norm':float(np.linalg.norm(right[c])),'CPU_vector_norm':float(np.linalg.norm(left[c]))})
report={'subject':'CON07','scope':'Existing same-input CPU tensor diagnostic vs its own official reference; no independent raw-chain FA comparison, no tensor refit/model solver/GPU','hostname':socket.gethostname(),'source_sha256':sha(Path(__file__)),'inputs':{k:{'path':str(v),'sha256':sha(v)} for k,v in files.items()},'brain_mask_voxels':int(mask.sum()),'valid_vector_pairs':int(valid.sum()),'invalid_vector_pairs_in_mask':int((mask&~valid).sum()),'antipodal_angle_degrees_quantiles':{str(q):float(np.quantile(angle,q)) for q in [0,.5,.9,.95,.99,.999,.9999,1]},'descriptive_counts_angle_gt_degrees':{str(t):int((angle>t).sum()) for t in [1e-5,.001,.01,.1,1,5,10,20,40]},'top10':rows,'geometry':{'shape':list(base.shape),'affine':base.affine.tolist(),'axcodes':list(nib.aff2axcodes(base.affine))},'interpretation':['The sole angle >0.001 degree occurs at the same voxel as the maximum FA difference. Official saved vector matches the absmax eigenvector of its saved tensor (antipodal angle 0).','The official tensor top absolute eigenvalue gap is 0.0005813513481298582, relative gap 0.07586837436004422; it is not an exactly repeated top eigenvalue. CPU FA 3.7291164600716797e-10 is consistent with an almost isotropic tensor, but CPU eigenvalues were not saved and the exact gap/cause is unverified.','Input DWI and gradient SHA match the existing same-input diagnostic and official contract, geometry matches, and the other 109400 finite pairs have angle <=0.001 degree. A global axis/gradient mismatch is not supported by this pattern; a specific cause is not established.'],'limitations':['CPU diagnostic saved FA and direction but no tensor coefficients/eigenvalues; CPU eigengap cannot be recovered from these outputs. No tensor refit was performed.','Eigenanalysis uses only existing official float32 tensor, float64 NumPy eigh; no numeric output or selection threshold changed. Counts at listed angle cutoffs are descriptive only.','A single official eigengap does not by itself identify the cause of the CPU vector difference; gradient input SHA matches prior diagnostic, and output geometry is checked, but CPU tensor coefficients remain unavailable.'],'tensor_coefficient_order_source':'https://userdocs.mrtrix.org/en/3.0.3/reference/commands/dwi2tensor.html'}
out.parent.mkdir(parents=True,exist_ok=True);out.write_text(json.dumps(report,indent=2,allow_nan=False)+'\n');print(json.dumps({'quantiles':report['antipodal_angle_degrees_quantiles'],'counts':report['descriptive_counts_angle_gt_degrees'],'maximum':rows[0]},indent=2))
