name: fnit-recon-all-cpp
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip>=23
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - cuda-version=11.8
  - cuda-nvcc=11.8
  - cuda-cudart-dev=11.8
  - numpy<2
  - scipy>=1.9
  - statsmodels=0.14.5
  - pandas=2.2.3
  - scikit-learn=1.5.2
  - dipy=1.12.1
  - h5py>=3.8
  - nibabel>=5
  - pyyaml>=6
  - numba>=0.59
  - tifffile>=2023.7
  - imagecodecs=2024.12.30
  - gcc_linux-64=11
  - gxx_linux-64=11
  - gfortran_linux-64=11
  - cmake
  - ninja
  - make
  - pkg-config
  - libitk=5.4.7
  - libitk-devel=5.4.7
  - eigen
  - libpng
  - libtiff
  - fftw
  - zlib
  - https://conda.anaconda.org/conda-forge/noarch/sysroot_linux-64-2.17-h0157908_18.conda
  - pip:
      - surfa==0.6.3
      - -e .[recon-all-python-stages]
