#!/bin/sh

#   Copyright (C) 2007 University of Oxford
#
#   SHCOPYRIGHT

echo
echo "Error - bedpost has been superceded by bedpostx! Please instead run:"
if [ "$1" != "" ];then
    echo bedpostx $@ -n 1
else
    echo bedpostx \<dir\> -n 1
fi
echo

