#!/bin/sh

#   Copyright (C) 2007 University of Oxford
#
#   SHCOPYRIGHT

echo
echo "Error - probtrack has been superceded by probtrackx!"
echo "Please see the FDT documentation for the new probtrackx syntax"
echo

